### ISSUE TITLE
[Bug] Unable to run NPM install

### ISSUE THREAD

**Issue by jasoncasares** [creativetimofficial/ct-paper-kit-pro-react#11] opened 2021-05-12 03:33 UTC
### Version
1.3.0
### Reproduction link
https://demos.creative-tim.com/paper-kit-pro-react/?_ga=2.174268578.1001314550.1620685783-1681620386.1620445543#/documentation/introduction
### Operating System
MAC
### Device
Macbook Pro
### Browser & Version
Safari 14.0.3
### Steps to reproduce
Install NodeJs from NodeJs Official Page
Go to creative tim website and login into your account
Go to the downloads section of your account (be sure to be logged into your account)
Press the download button near Paper Kit PRO React product (this will download onto your computer a zip file)
Unzip the downloaded file to a folder in your computer
Open Terminal
Go to your file project (where you've unzipped the product)
Run in terminal
npm install
### What is expected?
Install Dependencies with "npm install" and be able to run "npm start"
### What is actually happening?
Received several errors when running "npm install".

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: paper-kit-pro-react@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.5.0" from react-datetime@3.0.4
npm ERR! node_modules/react-datetime
npm ERR!   react-datetime@"3.0.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

---
### Solution
npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: paper-kit-pro-react@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.5.0" from react-datetime@3.0.4
npm ERR! node_modules/react-datetime
npm ERR!   react-datetime@"3.0.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

### Additional comments
Attempted to run npm install --legacy-peer-deps
but received more errors

Attempted to run npm run install:clean
Attempted to run npm run install:clean --legacy-peer-deps

**Comment by einazare** [comment] 2021-05-12 05:44
Hello there, @jasoncasares ,

Thank you for your interest in working with our products.
Please download and install NodeJS LTS version from the official website: https://nodejs.org/en/
And also, after you download the NodeJS LTS version and install it, please do not change the npm version that NodeJS LTS version comes with. On my machine it looks like this:
<img width="330" alt="Screen Shot 2021-05-12 at 8 44 12 AM" src="https://user-images.githubusercontent.com/26245512/117924330-3c6ac680-b2fe-11eb-9b25-1bf6a5391768.png">

Let me know if this solved the issue.

Best,
Manu

**Comment by jasoncasares** [comment] 2021-05-12 21:42
This was done in the beginning and did not solve the problem.

**Comment by einazare** [comment] 2021-05-13 09:18
Hello again, @jasoncasares ,

Can you please provide me with the following video: 
* Download the product
* Unzip the product
* Open terminal and cd into the project
* Run node -v
* Run npm -v
* Run npm install
* Run npm start
* Showcase the issue

Best,
Manu

**Comment by jasoncasares** [comment] 2021-05-14 22:51
I found the issue.  There was a peer dependency issue with "react-datetime" found below.

https://github.com/arqex/react-datetime/pull/764/commits/e492d510a8c867d071161d72be1b2bf240f3739c

I ran "npm install --force" which solved the issue.

**Comment by TRONJon** [comment] 2022-05-23 09:55
This is still an ongoing issue and this kit no longer works with the current LTS of node. Please can we get a fix ASAP?

**Comment by sajadevo** [comment] 2022-08-19 14:06
Hi guys,

The issue is fixed on v1.3.1.

Best,
Sajad

**Closed as completed by sajadevo** 2022-08-19 14:06 UTC

**Comment by TRONJon** [comment] 2022-08-21 09:32
> 

Hi Sajad,
The latest release of this template available to download doesn't contain the package-lock.json, without this file the template will break as soon as one of the dependant packages changes and someone does a fresh install. The issue you have marked as 'Closed' will come back very quickly. 

Is there a reason for not including package-lock.json in the templates?

**Comment by sajadevo** [comment] 2022-08-21 21:14
> > 
> 
> Hi Sajad, The latest release of this template available to download doesn't contain the package-lock.json, without this file the template will break as soon as one of the dependant packages changes and someone does a fresh install. The issue you have marked as 'Closed' will come back very quickly.
> 
> Is there a reason for not including package-lock.json in the templates?

Don't worry @TRONJon,

The packages doesn't contains any ^ sign to download the latest version it will only download the version that is mentioned for a dependency also the issue was coming from peer-dependency with react that I've added react as a peer-dependency.
